const datas = [
  {
    id: 1,
    firstName: "Alex",
    lastName: "A",
    startDate: "12/08/2021",
    department: "Department",
    dateOfBirth: "31/03/2002",
    street: "Street",
    city: "City",
    state: "State",
    zipCode: "33000",
  },
  {
    id: 2,
    firstName: "Jack",
    lastName: "B",
    startDate: "14/07/1990",
    department: "Department",
    dateOfBirth: "01/01/1968",
    street: "Street",
    city: "City",
    state: "State",
    zipCode: "75000",
  },
  {
    id: 3,
    firstName: "Suzie",
    lastName: "C",
    startDate: "12/12/2021",
    department: "Department",
    dateOfBirth: "23/12/1980",
    street: "Street",
    city: "City",
    state: "State",
    zipCode: "31000",
  },
  {
    id: 4,
    firstName: "Julia",
    lastName: "D",
    startDate: "23/09/2020",
    department: "Department",
    dateOfBirth: "24/02/1998",
    street: "Street",
    city: "City",
    state: "State",
    zipCode: "56000",
  },
  {
    id: 5,
    firstName: "Alex",
    lastName: "A",
    startDate: "12/08/2021",
    department: "Department",
    dateOfBirth: "31/03/2002",
    street: "Street",
    city: "City",
    state: "State",
    zipCode: "33000",
  },
  {
    id: 6,
    firstName: "Jack",
    lastName: "B",
    startDate: "14/07/1990",
    department: "Department",
    dateOfBirth: "01/01/1968",
    street: "Street",
    city: "City",
    state: "State",
    zipCode: "75000",
  },
  {
    id: 7,
    firstName: "Suzie",
    lastName: "C",
    startDate: "12/12/2021",
    department: "Department",
    dateOfBirth: "23/12/1980",
    street: "Street",
    city: "City",
    state: "State",
    zipCode: "31000",
  },
  {
    id: 8,
    firstName: "Julia",
    lastName: "D",
    startDate: "23/09/2020",
    department: "Department",
    dateOfBirth: "24/02/1998",
    street: "Street",
    city: "City",
    state: "State",
    zipCode: "56000",
  },
  {
    id: 9,
    firstName: "Alex",
    lastName: "A",
    startDate: "12/08/2021",
    department: "Department",
    dateOfBirth: "31/03/2002",
    street: "Street",
    city: "City",
    state: "State",
    zipCode: "33000",
  },
  {
    id: 10,
    firstName: "Jack",
    lastName: "B",
    startDate: "14/07/1990",
    department: "Department",
    dateOfBirth: "01/01/1968",
    street: "Street",
    city: "City",
    state: "State",
    zipCode: "75000",
  },
  {
    id: 11,
    firstName: "Suzie",
    lastName: "C",
    startDate: "12/12/2021",
    department: "Department",
    dateOfBirth: "23/12/1980",
    street: "Street",
    city: "City",
    state: "State",
    zipCode: "31000",
  },
  {
    id: 12,
    firstName: "Julia",
    lastName: "D",
    startDate: "23/09/2020",
    department: "Department",
    dateOfBirth: "24/02/1998",
    street: "Street",
    city: "City",
    state: "State",
    zipCode: "56000",
  },
];

const columns = [
  { title: "First Name", data: "firstName" },
  { title: "Last Name", data: "lastName" },
  { title: "Start Date", data: "startDate" },
  { title: "Department", data: "department" },
  { title: "Date of Birth", data: "dateOfBirth" },
  { title: "Street", data: "street" },
  { title: "City", data: "city" },
  { title: "State", data: "state" },
  { title: "Zip Code", data: "zipCode" },
];

export { datas, columns };
